sidebar:
  widgets:
    default_layout: [welcome, recent]
  menu:
    post: '[博客](/)'
    wiki: '[专栏](/wiki/)'
    notes: '[便笺](/notes/)'
    about: '[关于](/about/)'

comments:
  service: beaudar
  beaudar:
    repo: klenkiven/blog-comments

footer:
  social:
    github:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/klenkiven
    comments:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments
  sitemap:
    '博客主页':
      - '[主页](/)'
    '博客':
      - '[近期发布](/blog/)'
      - '[分类](/categories/)'
      - '[标签](/tags/)'
      - '[归档](/archives/)'
    'Wiki':
      - '[所有专栏](/wiki/)'
      - '[便签](/notes/)'
    '联系我们':
      - '[Email](mailto:wzl709@outlook.com)'
      - '[GitHub](https://github.com/klenkiven)'
